enable: true
version: 14
push: ''
account:
  cookie: ''
  stuid: ''
  stoken: ''
  mid: ''
device:
  name: Xiaomi MI 6
  model: Mi 6
  id: ''
  fp: ''
mihoyobbs:
  enable: true
  checkin: true
  checkin_list:
  - 5
  - 2
  read: true
  like: true
  cancel_like: true
  share: true
games:
  cn:
    enable: true
    useragent: Mozilla/5.0 (Linux; Android 12; Unspecified Device) AppleWebKit/537.36
      (KHTML, like Gecko) Version/4.0 Chrome/103.0.5060.129 Mobile Safari/537.36
    retries: 3
    genshin:
      checkin: true
      black_list: []
      auto_checkin: false
    honkai2:
      checkin: false
      black_list: []
    honkai3rd:
      checkin: false
      black_list: []
    tears_of_themis:
      checkin: false
      black_list: []
    honkai_sr:
      checkin: true
      black_list: []
    zzz:
      checkin: true
      black_list: []
  os:
    enable: false
    cookie: ''
    lang: zh-cn
    genshin:
      checkin: false
      black_list: []
    honkai3rd:
      checkin: false
      black_list: []
    tears_of_themis:
      checkin: false
      black_list: []
    honkai_sr:
      checkin: false
      black_list: []
    zzz:
      checkin: false
      black_list: []
cloud_games:
  cn:
    enable: false
    genshin:
      enable: false
      token: ''
    zzz:
      enable: false
      token: ''
  os:
    lang: zh-cn
    enable: false
    genshin:
      enable: false
      token: ''
competition:
  enable: false
  genius_invokation:
    enable: false
    account: []
    checkin: false
    weekly: false
