name: Daily Sign-in

on:
  schedule:
    - cron: '0 16 * * *'
  workflow_dispatch:  # 允许手动触发

jobs:
  signin:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1  # 只获取最新的提交，加快克隆速度
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'  # 启用pip缓存
        
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        
    - name: Update cookie
      run: |
        sed -i "s/cookie: .*/cookie: ${{ secrets.COOKIE }}/" config/config.yaml
      
    - name: Run sign-in script
      run: |
        python main.py
      env:
        TZ: Asia/Shanghai
