name: Daily Sign-in

on:
  schedule:
    - cron: '0 16 * * *'
  workflow_dispatch:  # 允许手动触发

jobs:
  signin:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1  # 只获取最新的提交，加快克隆速度
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'  # 启用pip缓存
        
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        
    - name: Update cookie
      run: |
        python -c "
        import yaml
        with open('config/config.yaml', 'r', encoding='utf-8') as f:
            config = yaml.safe_load(f)
        config['account']['cookie'] = '${{ secrets.COOKIE }}'
        config['account']['stoken'] = '${{ secrets.STOKEN }}'
        with open('config/config.yaml', 'w', encoding='utf-8') as f:
            yaml.dump(config, f, allow_unicode=True)
        "
      
    - name: Run sign-in script
      run: |
        python main.py
      env:
        TZ: Asia/Shanghai
